blacklist = [
    'chat.whatsapp',
    'wa.me',
    't.me',
    'api.whatsapp',
    'kwai.app',
    'nos uma visita',
    'financiamento negado',
    'veículos novos e semi',
    'faça seu orçamento',
    'veículos semi-novo',
    'plano sem juro',
    'planos sem juro',
    'serviços de frete',
    'adestramento inteligente',
    'ensine seu cão',
    'ensine seu cachorro',
    'raissa sampaio',
    'você quer sabe como ganhar'
]